---
downstream_package_name: rpmdeplint
upstream_project_url: https://github.com/fedora-ci/rpmdeplint

actions:
  create-archive:
    - "python3 -m build --sdist --outdir ."
    - "sh -c 'echo rpmdeplint-$(hatch version).tar.gz'"
  get-current-version:
    - "hatch version"

srpm_build_deps:
  - python3-build
  - hatch
  - python3-hatch-vcs

upstream_tag_template: rpmdeplint-{version}

jobs:
  - job: copr_build
    trigger: pull_request
    targets:
      - fedora-all
      - epel-9
  - job: copr_build
    trigger: commit
    branch: main
    targets:
      - fedora-all
      - epel-9
    owner: "@osci"
    project: rpmdeplint

  - job: tests
    trigger: pull_request
    targets:
      - fedora-all
      - epel-9
